# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.py'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import clients
from ventana import *
import sys
import var, events
from ventanaaviso import *
class DialogSalir(QtWidgets.QDialog):
    def __init__(self):
        '''
        Clase que instancia la ventana de aviso salir
        '''
        super(DialogSalir, self).__init__()
        var.dlgsalir = Ui_Dialog()
        var.dlgsalir.setupUi(self)



class Main(QtWidgets.QMainWindow):

    def __init__(self):
        super(Main, self).__init__()
        var.ui = Ui_MainWindow()
        var.ui.setupUi(self)

        '''
        Conexión con eventos Salir
        '''
        var.ui.actionSalir.triggered.connect(events.Eventos.Salir)

        '''
        conexión con los eventos
      
        
        var.ui.btnAceptar.clicked.connect(events.Eventos.Saludo)

        '''
        '''
        
        Evento comprobar dni al salir del texto
        
        '''
        var.ui.txtDNI.editingFinished.connect(clients.Clientes.validarDNI)
'''
        var.ui.actionCrear_Backup.triggered.connect(events.Eventos.crearBackup())
'''

if __name__ == '__main__':
    app = QtWidgets.QApplication([])
    window = Main()
    desktop = QtWidgets.QApplication.desktop()
    x = (desktop.width() - window.width()) // 2
    y = (desktop.height() - window.height()) // 2
    window.move(x, y)
    var.dlgsalir = DialogSalir()
    window.show()
    sys.exit(app.exec())

